spring:
  profiles:
    active: local

  config:
    import:
      - optional:classpath:/config/${spring.profiles.active}/application-db.yaml
      - optional:classpath:/config/${spring.profiles.active}/application-security.yaml
