spring:
  profiles:
    active: local

include:
  - config/${spring.profiles.active}/application-db.yaml
  - config/${spring.profiles.active}/application-security.properties

jwt:
  key:
    access: TE9DQUxfSldUX0FDQ0VTU19UT0tFTl9TRUNSRVRfS0VZ
  access-token-validity-in-seconds: 1800
